name: macOS Test

on:
  workflow_dispatch:

jobs:
 build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show macOS Version
        run: sw_vers

      - name: Install Dependencies
        run: npm install

      - name: Verify Electron Builder
        run: npx electron-builder --version

      - name: Build macOS DMG
        run: npx electron-builder --mac dmg

      - name: List Dist Files
        run: ls -la dist

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: CybrxAgent-macOS
          path: dist/
